
		<?php
		/* 
		 * phpMyAdmin Configuration File
		 * Generated by : phpMyAdmin v3.3.7 for Prestashop v1.4.7.0 by caparuni
		 * Date : April 10, 2012 - 5:30 pm
		*/
		
		$i = 0;
		$i++;
		$cfg['Servers'][$i]['host'] = 'localhost';
		$cfg['Servers'][$i]['user'] = 'webdev';
		$cfg['Servers'][$i]['password'] = 'password';
		$cfg['Servers'][$i]['only_db'] = 'goodjobstore';
		
		$cfg['Servers'][$i]['extension'] = 'mysql';
		$cfg['Servers'][$i]['connect_type'] = 'tcp';
		$cfg['Servers'][$i]['compress'] = false;
		$cfg['Servers'][$i]['auth_type'] = 'config';
		$cfg['RightDisplayServers'] = false;
		$cfg['ShowServerInfo'] = false;
		?>